version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
    - "2181"

  kafka:
    image: wurstmeister/kafka
    depends_on:
    - zookeeper
    ports:
      - "9092-9095:9092"
    environment:
      # you need to change this to match your own ip or host name
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.216
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
